# Comparison of Written and Rated Reviews #

In [1]:
!pip install opendatasets
import opendatasets as od

In [2]:
od.download("https://www.kaggle.com/datafiniti/consumer-reviews-of-amazon-products")

Skipping, found downloaded files in ".\consumer-reviews-of-amazon-products" (use force=True to force download)


In [3]:
import pandas as pd
import numpy as np

## Preprocessing ##

In [4]:
df = pd.read_csv("C:\\Users\\zoheb\\Dev\\ML Project\\K-nearest Neighbor\\consumer-reviews-of-amazon-products\\1429_1.csv")
df

C:\Users\zoheb\AppData\Local\Temp\ipykernel_15436\1728318176.py:1: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:\\Users\\zoheb\\Dev\\ML Project\\K-nearest Neighbor\\consumer-reviews-of-amazon-products\\1429_1.csv")


id  \
0      AVqkIhwDv8e3D1O-lebb   
1      AVqkIhwDv8e3D1O-lebb   
2      AVqkIhwDv8e3D1O-lebb   
3      AVqkIhwDv8e3D1O-lebb   
4      AVqkIhwDv8e3D1O-lebb   
...                     ...   
34655  AVpfiBlyLJeJML43-4Tp   
34656  AVpfiBlyLJeJML43-4Tp   
34657  AVpfiBlyLJeJML43-4Tp   
34658  AVpfiBlyLJeJML43-4Tp   
34659  AVpfiBlyLJeJML43-4Tp   

                                                    name       asins   brand  \
0      All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  B01AHB9CN2  Amazon   
1      All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  B01AHB9CN2  Amazon   
2      All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  B01AHB9CN2  Amazon   
3      All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  B01AHB9CN2  Amazon   
4      All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...  B01AHB9CN2  Amazon   
...                                                  ...         ...     ...   
34655                                                NaN  B006GWO5WK  Amazon   
34656                                                NaN  B006GWO5WK  Amazon   
34657                                                NaN  B006GWO5WK  Amazon   
34658                                                NaN  B006GWO5WK  Amazon   
34659                                                NaN  B006GWO5WK  Amazon   

                                              categories  \
0      Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1      Electronics,iPad & Tablets,All Tablets,Fire Ta...   
2      Electronics,iPad & Tablets,All Tablets,Fire Ta...   
3      Electronics,iPad & Tablets,All Tablets,Fire Ta...   
4      Electronics,iPad & Tablets,All Tablets,Fire Ta...   
...                                                  ...   
34655  Computers/Tablets & Networking,Tablet & eBook ...   
34656  Computers/Tablets & Networking,Tablet & eBook ...   
34657  Computers/Tablets & Networking,Tablet & eBook ...   
34658  Computers/Tablets & Networking,Tablet & eBook ...   
34659  Computers/Tablets & Networking,Tablet & eBook ...   

                                                    keys  \
0      841667104676,amazon/53004484,amazon/b01ahb9cn2...   
1      841667104676,amazon/53004484,amazon/b01ahb9cn2...   
2      841667104676,amazon/53004484,amazon/b01ahb9cn2...   
3      841667104676,amazon/53004484,amazon/b01ahb9cn2...   
4      841667104676,amazon/53004484,amazon/b01ahb9cn2...   
...                                                  ...   
34655  newamazonkindlefirehd9wpowerfastadaptercharger...   
34656  newamazonkindlefirehd9wpowerfastadaptercharger...   
34657  newamazonkindlefirehd9wpowerfastadaptercharger...   
34658  newamazonkindlefirehd9wpowerfastadaptercharger...   
34659  newamazonkindlefirehd9wpowerfastadaptercharger...   

                       manufacturer              reviews.date  \
0                            Amazon  2017-01-13T00:00:00.000Z   
1                            Amazon  2017-01-13T00:00:00.000Z   
2                            Amazon  2017-01-13T00:00:00.000Z   
3                            Amazon  2017-01-13T00:00:00.000Z   
4                            Amazon  2017-01-12T00:00:00.000Z   
...                             ...                       ...   
34655  Amazon Digital Services, Inc      2012-09-18T00:00:00Z   
34656  Amazon Digital Services, Inc      2012-11-21T00:00:00Z   
34657  Amazon Digital Services, Inc      2012-10-19T00:00:00Z   
34658  Amazon Digital Services, Inc      2012-10-31T00:00:00Z   
34659  Amazon Digital Services, Inc      2012-12-23T00:00:00Z   

          reviews.dateAdded  \
0      2017-07-03T23:33:15Z   
1      2017-07-03T23:33:15Z   
2      2017-07-03T23:33:15Z   
3      2017-07-03T23:33:15Z   
4      2017-07-03T23:33:15Z   
...                     ...   
34655                   NaN   
34656                   NaN   
34657                   NaN   
34658                   NaN   
34659                   NaN   

                                        reviews.dateSeen  ...  \
0      2017-06-07T09:04:00.000

In [5]:
df = df[['reviews.text', 'reviews.rating']]
df = df.drop_duplicates()
df = df.dropna()
df

reviews.text  reviews.rating
0      This product so far has not disappointed. My c...             5.0
1      great for beginner or experienced person. Boug...             5.0
2      Inexpensive tablet for him to use and learn on...             5.0
3      I've had my Fire HD 8 two weeks now and I love...             4.0
4      I bought this for my grand daughter when she c...             5.0
...                                                  ...             ...
34655  This is not appreciably faster than any other ...             3.0
34656  Amazon should include this charger with the Ki...             1.0
34657  Love my Kindle Fire but I am really disappoint...             1.0
34658  I was surprised to find it did not come with a...             1.0
34659  to spite the fact that i have nothing but good...             1.0

[34626 rows x 2 columns]

### Balancing Data Frame

In [6]:
notFive = df.drop(df[df['reviews.rating'] == 5.0].index)
notFive = notFive.reset_index(drop=True)
notFive

reviews.text  reviews.rating
0      I've had my Fire HD 8 two weeks now and I love...             4.0
1      Great for e-reading on the go, nice and light ...             4.0
2      Not easy for elderly users cease of ads that p...             4.0
3      Wanted my father to have his first tablet and ...             4.0
4      nice reader. almost perfect for what i want/ne...             4.0
...                                                  ...             ...
10847  This is not appreciably faster than any other ...             3.0
10848  Amazon should include this charger with the Ki...             1.0
10849  Love my Kindle Fire but I am really disappoint...             1.0
10850  I was surprised to find it did not come with a...             1.0
10851  to spite the fact that i have nothing but good...             1.0

[10852 rows x 2 columns]

In [7]:
NewnotFive = pd.DataFrame()
for i in range(3):
    NewnotFive = pd.concat([NewnotFive,notFive], axis = 0)
df = pd.concat([df,NewnotFive], axis = 0)
#df = pd.concat([df,notFive], axis = 0)
df

reviews.text  reviews.rating
0      This product so far has not disappointed. My c...             5.0
1      great for beginner or experienced person. Boug...             5.0
2      Inexpensive tablet for him to use and learn on...             5.0
3      I've had my Fire HD 8 two weeks now and I love...             4.0
4      I bought this for my grand daughter when she c...             5.0
...                                                  ...             ...
10847  This is not appreciably faster than any other ...             3.0
10848  Amazon should include this charger with the Ki...             1.0
10849  Love my Kindle Fire but I am really disappoint...             1.0
10850  I was surprised to find it did not come with a...             1.0
10851  to spite the fact that i have nothing but good...             1.0

[67182 rows x 2 columns]

In [8]:
import re
NON_ALPHANUM = re.compile(r'[\W]')
NON_ASCII = re.compile(r'[^a-z0-1\s]')
def normalize_texts(texts):
    normalized_texts = []
    for text in texts:
        lower = text.lower()
        no_punctuation = NON_ALPHANUM.sub(r' ', lower)
        no_non_ascii = NON_ASCII.sub(r'', no_punctuation)
        normalized_texts.append(no_non_ascii)
    return normalized_texts
        
df['reviews.text'] = normalize_texts(df['reviews.text'])

In [9]:
 df

reviews.text  reviews.rating
0      this product so far has not disappointed  my c...             5.0
1      great for beginner or experienced person  boug...             5.0
2      inexpensive tablet for him to use and learn on...             5.0
3      i ve had my fire hd  two weeks now and i love ...             4.0
4      i bought this for my grand daughter when she c...             5.0
...                                                  ...             ...
10847  this is not appreciably faster than any other ...             3.0
10848  amazon should include this charger with the ki...             1.0
10849  love my kindle fire but i am really disappoint...             1.0
10850  i was surprised to find it did not come with a...             1.0
10851  to spite the fact that i have nothing but good...             1.0

[67182 rows x 2 columns]

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=True)
cv.fit(df['reviews.text'])
X = cv.transform(df['reviews.text'])
X

<67182x13517 sparse matrix of type '<class 'numpy.int64'>'
	with 1663930 stored elements in Compressed Sparse Row format>

In [11]:
print(cv.vocabulary_)

{'this': 12010, 'product': 9156, 'so': 10949, 'far': 4353, 'has': 5465, 'not': 7999, 'disappointed': 3345, 'my': 7765, 'children': 2108, 'love': 7097, 'to': 12140, 'use': 12725, 'it': 6363, 'and': 610, 'like': 6921, 'the': 11935, 'ability': 94, 'monitor': 7628, 'control': 2625, 'what': 13142, 'content': 2598, 'they': 11977, 'see': 10410, 'with': 13260, 'ease': 3727, 'great': 5266, 'for': 4689, 'beginner': 1262, 'or': 8260, 'experienced': 4217, 'person': 8651, 'bought': 1564, 'as': 857, 'gift': 5037, 'she': 10571, 'loves': 7104, 'inexpensive': 6063, 'tablet': 11709, 'him': 5632, 'learn': 6788, 'on': 8174, 'step': 11299, 'up': 12670, 'from': 4840, 'nabi': 7777, 'he': 5512, 'was': 13019, 'thrilled': 12036, 'how': 5765, 'skype': 10809, 'already': 523, 've': 12812, 'had': 5377, 'fire': 4523, 'hd': 5498, 'two': 12453, 'weeks': 13097, 'now': 8039, 'is': 6345, 'value': 12785, 'we': 13064, 'are': 808, 'prime': 9096, 'members': 7375, 'that': 11925, 'where': 13154, 'shines': 10596, 'being': 1276,

## Playing around with Logistic Regression ##

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split


# X_train, X_val, y_train, y_val = train_test_split(
#     X, df['reviews.rating'], train_size = 0.75
# )

# for c in [0.01, 0.05, 0.25, 0.5, 1]:
    
#     lr = LogisticRegression(C=c)
#     lr.fit(X_train, y_train)
#     print ("Accuracy for C=%s: %s" 
#            % (c, accuracy_score(y_val, lr.predict(X_val))))

## K-Nearest Algorithm ##

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X, df['reviews.rating'], train_size = 0.75
)
    
knn = KNeighborsClassifier(n_neighbors=7)
 
knn.fit(X_train, y_train)
print ("Accuracy = %s" % (accuracy_score(y_val, knn.predict(X_val))))
cmForK = confusion_matrix(y_val, knn.predict(X_val))

Accuracy = 0.6105025005953798


## Naive Bayes

In [14]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
from sklearn.model_selection import train_test_split

mnb.fit(X_train, y_train)
print ("Accuracy = %s" % (accuracy_score(y_val, mnb.predict(X_val))))
cmforNB = confusion_matrix(y_val, mnb.predict(X_val))

Accuracy = 0.6547987616099071


## Linear SVM

In [15]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')
from sklearn.model_selection import train_test_split

clf.fit(X_train, y_train)
print ("Accuracy = %s" % (accuracy_score(y_val, clf.predict(X_val))))
confusion_matrix(y_val, clf.predict(X_val))

Accuracy = 0.7511907597046916


array([[ 389,    4,    3,    4,    3],
       [   0,  354,    4,   19,    2],
       [   7,   13, 1106,  330,   61],
       [   5,   11,   93, 7194, 1209],
       [  37,   45,  166, 2163, 3574]], dtype=int64)

## Confusion Matrix

In [16]:
print(cmForK)



[[ 168   38   17   77  103]
 [   6  187   10   99   77]
 [  16  113  633  436  319]
 [  33  300  204 6157 1818]
 [  25  262  152 2437 3109]]


In [17]:
print(cmforNB)

[[ 220    4   41  111   27]
 [  13  111   76  157   22]
 [  24    0  586  773  134]
 [  24   11  154 5996 2327]
 [  18    9   73 1800 4085]]
